Fix: Bug, if missing newline on last pos: Could not create fragment shader: 0(341) : error C0104: Unknown pre-processor directive #group WinBuild: added imageplugins Slider keyboard shortcuts